[memory]
memory_limit = 512M

[display_errors]
display_errors = Off

[date]
date.timezone = UTC

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256
opcache.revalidate_freq = 60
opcache.jit = tracing
opcache.jit_buffer_size = 100M
